"""empty message

Revision ID: 087dff73cca2
Revises: 
Create Date: 2021-09-13 22:29:59.793557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '087dff73cca2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='系统管理员',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_user', 'account',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               nullable=True,
               comment=None,
               existing_comment='账号')
    op.alter_column('sys_user', 'password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               nullable=True,
               comment=None,
               existing_comment='密码')
    op.alter_column('sys_user', 'user_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               nullable=True,
               comment=None,
               existing_comment='用户名')
    op.alter_column('sys_user', 'phone',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               nullable=True,
               comment=None,
               existing_comment='手机号')
    op.alter_column('sys_user', 'mail',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               nullable=True,
               comment=None,
               existing_comment='邮箱')
    op.alter_column('sys_user', 'status',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='账号状态：1.正常 2.禁用 3.删除')
    op.alter_column('sys_user', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('sys_user', 'status',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='账号状态：1.正常 2.禁用 3.删除')
    op.alter_column('sys_user', 'mail',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               nullable=False,
               comment='邮箱')
    op.alter_column('sys_user', 'phone',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               nullable=False,
               comment='手机号')
    op.alter_column('sys_user', 'user_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               nullable=False,
               comment='用户名')
    op.alter_column('sys_user', 'password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               nullable=False,
               comment='密码')
    op.alter_column('sys_user', 'account',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               nullable=False,
               comment='账号')
    op.alter_column('sys_user', 'id',
               existing_type=mysql.INTEGER(),
               comment='系统管理员',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
